### ISSUE TITLE
Project Design

### ISSUE THREAD

**Issue by TomL000** [JeanOnDaGIT/four-in-a-row#10]

**Comment by TomL000** [comment]
Create a flow chart

**Comment by TomL000** [comment]
Create pseudocode to get the overall flow of the code

**Comment by TomL000** [comment]
HCI - 
Create a wireframe, storyboard and a description of the functionality of the project.
Record the functionality testing within a data table
Animation?
How can we be inclusive or accessible in our project.

**Comment by JeanOnDaGIT** [comment]
Finished my part of the Project Design, will wait on Seb writing (Red) and Jack (Yellow) who is also assisted with me

**Comment by TomL000** [comment]
> Make a record of data structures, records and how they are used

Started on this, returning home as I'm the only one present currently.
